services:
  sql-server:
    # see https://github.com/microsoft/mssql-docker
    # see https://mcr.microsoft.com/en-us/artifact/mar/mssql/server
    # see https://hub.docker.com/r/microsoft/mssql-server
    image: mcr.microsoft.com/mssql/server:2025-latest
    hostname: sql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=HeyH0Password
      - MSSQL_PID=express
    volumes:
      - sql-server:/var/opt/mssql
    healthcheck:
      test: >
        /opt/mssql-tools18/bin/sqlcmd
        -t 10
        -C
        -S localhost
        -U sa
        -P "$$MSSQL_SA_PASSWORD"
        -d master
        -b
        -Q 'select 1'
        || exit 1
      start_period: 1m
      start_interval: 10s
      interval: 30s
      timeout: 10s
      retries: 5
  sql-server-init:
    build:
      context: sql-server-init
    environment:
      - MSSQL_SA_PASSWORD=HeyH0Password
    depends_on:
      sql-server:
        condition: service_healthy
  dotnet-client:
    build:
      context: dotnet-client
    environment:
      - MSSQL_CONNECTION_STRING=Server=sql-server,1433; TrustServerCertificate=True; Database=example; User ID=example; Password=HeyH0Password
    depends_on:
      sql-server-init:
        condition: service_completed_successfully
  go-client:
    build:
      context: go-client
    environment:
      - MSSQL_CONNECTION_STRING=Server=sql-server,1433; TrustServerCertificate=True; Database=example; User ID=example; Password=HeyH0Password
    depends_on:
      sql-server-init:
        condition: service_completed_successfully
  java-client:
    build:
      context: java-client
    environment:
      - MSSQL_CONNECTION_STRING=jdbc:sqlserver://sql-server:1433;trustServerCertificate=true;database=example;user=example;password=HeyH0Password
    depends_on:
      sql-server-init:
        condition: service_completed_successfully
  python-client:
    build:
      context: python-client
    environment:
      - MSSQL_CONNECTION_STRING=Server=sql-server,1433; TrustServerCertificate=yes; Database=example; Uid=example; Pwd=HeyH0Password
    depends_on:
      sql-server-init:
        condition: service_completed_successfully
volumes:
  sql-server:
